---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices6
  namespace: micro6
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: microservices6
    spec:
      containers:
      - name: microservices6
        image: alnroldan/microservices6:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: microservices6
---
apiVersion: v1
kind: Service
metadata:
  name: microservices6
  namespace: micro6
spec:  
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: microservices6